version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/gookit/color
    versions:
    - 1.3.6
    - 1.3.7
    - 1.3.8
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.1
    - 1.1.3
  - dependency-name: github.com/rhysd/go-github-selfupdate
    versions:
    - 1.2.3
  - dependency-name: github.com/hashicorp/go-getter
    versions:
    - 1.5.2
  - dependency-name: gopkg.in/yaml.v2
    versions:
    - 2.4.0
